name: Build Melt Kernel (Redmi Note 12 Turbo)

on:
  workflow_dispatch:

jobs:
  build:
    name: RedmiNote12Turbo-${{ matrix.ksu_status }}
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        ksu_status: [ "WithKSU", "NoKSU" ]

    steps:
    # 彻底解决磁盘撑爆问题，腾出 30GB+ 空间
    - name: 极限清理磁盘空间
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap: false

    - name: Setup SWAP
      uses: pierotofy/set-swap-space@master
      with:
          swap-size-gb: 16
          
    - name: 准备环境
      run: |
        sudo apt-get update
        sudo apt-get install -y git bc build-essential flex bison libssl-dev libelf-dev clang lld llvm python3 zip xz-utils python3-pip

    - name: 编译器缓存
      id: cache-llvm
      uses: actions/cache@v4
      with:
        path: ~/build_toolchain/llvm-22.1.8-x86_64
        key: llvm-22.1.8-linux-x64

    - name: 下载 LLVM 22.1.8 编译器
      if: steps.cache-llvm.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/build_toolchain/llvm-22.1.8-x86_64
        cd ~/build_toolchain/llvm-22.1.8-x86_64
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.8/LLVM-22.1.8-Linux-X64.tar.xz
        tar -xf LLVM-22.1.8-Linux-X64.tar.xz --strip-components=1
        rm LLVM-22.1.8-Linux-X64.tar.xz

    - name: 检出源码 (Melt Kernel bouquet)
      run: |
        cd $GITHUB_WORKSPACE
        git clone --depth=1 https://github.com/Pzqqt/android_kernel_xiaomi_marble.git -b bouquet sm8450
        sed -i 's/ -dirty//g' sm8450/scripts/setlocalversion

    - name: 集成 KernelSU & SUSFS
      if: ${{ matrix.ksu_status == 'WithKSU' }}
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android12-5.10 patch
        
        echo "CONFIG_KSU=y" >> $GITHUB_WORKSPACE/sm8450/arch/arm64/configs/marble_defconfig
        echo "CONFIG_KSU_SUSFS=y" >> $GITHUB_WORKSPACE/sm8450/arch/arm64/configs/marble_defconfig
        
        cd $GITHUB_WORKSPACE/sm8450
        curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash
        
        cp $GITHUB_WORKSPACE/patch/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch $GITHUB_WORKSPACE/sm8450/
        cp $GITHUB_WORKSPACE/patch/kernel_patches/fs/* $GITHUB_WORKSPACE/sm8450/fs/
        cp $GITHUB_WORKSPACE/patch/kernel_patches/include/linux/* $GITHUB_WORKSPACE/sm8450/include/linux/
        patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch

    - name: 集成 Re:Kernel 基础补丁 (Integrate)
      run: |
        cd $GITHUB_WORKSPACE
        git clone -b upstream/v9.2 https://github.com/myflavor/ReKernel-X.git rekernel_tmp
        cp -r rekernel_tmp/Integrate/* $GITHUB_WORKSPACE/sm8450/
        rm -rf rekernel_tmp
        
        cd $GITHUB_WORKSPACE/sm8450
        chmod +x patches.sh
        ./patches.sh

    - name: 集成 Re:Kernel LKM 源码 (同目录寄生内建版)
      run: |
        cd $GITHUB_WORKSPACE
        git clone -b main https://github.com/myflavor/ReKernel-X.git rekernel_lkm
        
        mkdir -p $GITHUB_WORKSPACE/sm8450/drivers/android/rekernel
        cp -r rekernel_lkm/LKM-Source/* $GITHUB_WORKSPACE/sm8450/drivers/android/rekernel/
        rm -rf rekernel_lkm
        
        cd $GITHUB_WORKSPACE/sm8450/drivers/android
        echo "obj-y += rekernel/rkx.o rekernel/rkx_genl.o rekernel/rkx_netuid.o rekernel/rkx_frozen.o rekernel/rkx_binder.o rekernel/rkx_signal.o rekernel/rkx_netfilter.o rekernel/rkx_binder_kp.o" >> Makefile
        
        echo "ccflags-y += -DRKX_VERSION=\\\"v9.2-BuiltIn\\\"" >> Makefile

    - name: 调用作者脚本编译并打包内核
      run: |
        cd $GITHUB_WORKSPACE/sm8450
        
        # 稳定的伪装软链接法，配合解除外部管理限制
        export PIP_BREAK_SYSTEM_PACKAGES=1
        sudo ln -sf /usr/bin/python3 /usr/bin/python2
        
        ln -sf ~/build_toolchain/llvm-22.1.8-x86_64/bin/clang ~/build_toolchain/llvm-22.1.8-x86_64/bin/aarch64-linux-gnu-clang
        
        chmod +x build_bouquet.sh
        ./build_bouquet.sh

    - name: 上传编译产物
      uses: actions/upload-artifact@v4
      with:
        name: Melt-Marble-${{ matrix.ksu_status }}-Artifacts
        path: |
          sm8450/*.zip
          sm8450/out/arch/arm64/boot/Image